# Generated by Django 6.0 on 2026-03-16 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.IntegerField(choices=[(9, '3x3'), (16, '4x4')], default=9)),
                ('duration_days', models.IntegerField(default=7, help_text='How many days to complete')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_items', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('LOVE', 'Love Message'), ('MOTIVATION', 'Motivation'), ('FUNNY', 'Funny'), ('ROMANTIC', 'Romantic'), ('ENCOURAGEMENT', 'Encouragement'), ('QUESTION', 'Conversation Question')], default='LOVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_score', models.IntegerField(default=0)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('reward_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='memories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MinigameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('REAL_CHALLENGE', 'Real Life Challenge'), ('VERSE_COMPLETION', 'Verse/Quote Completion'), ('TIMELINE', 'Timeline Challenge'), ('GUESS_PLACE', 'Guess the Place'), ('MEMORY_MATCH', 'Memory Match'), ('BINGO', 'Romantic Bingo'), ('QUEST_PROOF', 'Quest with Proof'), ('WOULD_RATHER', 'Would You Rather'), ('QUIZ', 'Custom Quiz'), ('ESCAPE_ROOM', 'Escape Room Puzzle'), ('CIPHER', 'Cipher/Cryptogram'), ('ANAGRAM', 'Anagram'), ('JIGSAW', 'Jigsaw Puzzle')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('MESSAGE', 'Special Message'), ('HINT', 'Hint for Puzzle'), ('UNLOCK', 'Unlock Content'), ('VOUCHER', 'Real-life Voucher'), ('COLLECTIBLE', 'Collectible Item'), ('BOOST', 'Streak Boost'), ('EXTRA_QUESTION', 'Extra Question Chance'), ('EXTRA_SPIN', 'Extra Spin Chance'), ('EXTRA_MEMORY', 'Extra Memory Sneak Peek'), ('EXTRA_DAILY_MESSAGE', 'Extra Daily Message Chance')], default='MESSAGE', max_length=50)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('is_reusable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StandaloneQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('default_points', models.IntegerField(default=10, help_text='Points awarded for a good answer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BingoSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='game.bingocard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collection_items/')),
                ('unlock_condition', models.TextField(help_text='Description of how to unlock')),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='game.collection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_locked', models.BooleanField(default=True)),
                ('points_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigames', to='game.level')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.minigametype')),
            ],
            options={
                'ordering': ['level__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_retry_daily', models.BooleanField(default=False, help_text='Bifează pentru a permite încă un mesaj zilnic azi')),
                ('can_retry_spin', models.BooleanField(default=False, help_text='Bifează pentru a permite încă o rotire la roată azi')),
                ('can_retry_question', models.BooleanField(default=False, help_text='Bifează pentru a permite încă o întrebare azi')),
                ('can_view_extra_memory', models.BooleanField(default=False, help_text='Bifează pentru a permite vizualizarea unei amintiri extra (sneak peek)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBingoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_squares', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bingocard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Answer'), ('MULTIPLE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('RATING', 'Confidence Rating'), ('ORDER', 'Put in Order')], default='TEXT', max_length=20)),
                ('correct_answer', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=10)),
                ('hint', models.TextField(blank=True)),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.minigame')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.playerprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.reward')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='completion_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.reward'),
        ),
        migrations.AddField(
            model_name='bingocard',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.reward'),
        ),
        migrations.CreateModel(
            name='SpinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
                ('reward_won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.reward')),
            ],
        ),
        migrations.CreateModel(
            name='SpinWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(help_text='Probability percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.reward')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('admin_score', models.IntegerField(default=0)),
                ('admin_feedback', models.TextField(blank=True, help_text='Optional feedback for the player')),
                ('is_graded', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.standalonequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.minigame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.collectionitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.CreateModel(
            name='DailyMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_date', models.DateField(auto_now_add=True)),
                ('was_claimed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dailymessage')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'shown_date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.minigame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'minigame')},
            },
        ),
    ]
